import {
  BarChart3,
  Bot,
  BrainCircuit,
  Cloud,
  Code2,
  Database,
  Globe,
  Layers,
  Megaphone,
  Palette,
  Server,
  Settings,
  Smartphone,
  Sparkles,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export type TechStackCategory = {
  id: string;
  title: string;
  icon: LucideIcon;
  items: string[];
};

export const techStackCategories: TechStackCategory[] = [
  {
    id: "programming-languages",
    title: "Programming Languages",
    icon: Code2,
    items: [
      "JavaScript (ES6+)",
      "TypeScript",
      "Python",
      "Java",
      "C++",
      "SQL",
      "HTML5",
      "CSS3",
    ],
  },
  {
    id: "frontend-development",
    title: "Frontend Development",
    icon: Layers,
    items: [
      "React.js",
      "Next.js",
      "React Native",
      "Tailwind CSS",
      "Styled Components",
      "Bootstrap",
      "Redux",
      "Responsive Web Design",
      "Progressive Web Apps (PWA)",
    ],
  },
  {
    id: "backend-development",
    title: "Backend Development",
    icon: Server,
    items: [
      "Node.js",
      "Express.js",
      "NestJS",
      "Django",
      "FastAPI",
      "Flask",
      "REST APIs",
      "GraphQL",
      "Microservices",
      "Authentication & Authorization (JWT, OAuth)",
    ],
  },
  {
    id: "mobile-app-development",
    title: "Mobile App Development",
    icon: Smartphone,
    items: [
      "React Native",
      "Cross-Platform Mobile Applications",
      "API Integration",
      "Firebase Integration",
      "Push Notifications",
    ],
  },
  {
    id: "ai-ml",
    title: "Artificial Intelligence & Machine Learning",
    icon: BrainCircuit,
    items: [
      "Artificial Intelligence (AI)",
      "Machine Learning (ML)",
      "Deep Learning",
      "Generative AI",
      "Large Language Models (LLMs)",
      "Prompt Engineering",
      "Retrieval-Augmented Generation (RAG)",
      "AI Chatbots",
      "LangChain",
      "FAISS",
      "OpenCV",
      "TensorFlow",
      "Keras",
      "Scikit-learn",
      "NumPy",
      "Pandas",
      "Matplotlib",
      "Statistical Analysis",
      "Predictive Modeling",
      "Data Wrangling",
      "Computer Vision",
    ],
  },
  {
    id: "data-science-analytics",
    title: "Data Science & Analytics",
    icon: BarChart3,
    items: [
      "Power BI",
      "Tableau",
      "Microsoft Excel (Advanced + AI)",
      "Data Visualization",
      "Business Intelligence",
      "Database Management Systems (DBMS)",
    ],
  },
  {
    id: "databases",
    title: "Databases",
    icon: Database,
    items: ["MongoDB", "MySQL", "PostgreSQL", "Firebase Firestore"],
  },
  {
    id: "cloud-devops",
    title: "Cloud, DevOps & Deployment",
    icon: Cloud,
    items: [
      "AWS (Lambda, S3, EC2)",
      "Vercel",
      "Docker",
      "Git",
      "GitHub",
      "Git Bash",
      "CI/CD",
      "Cloud Deployment",
    ],
  },
  {
    id: "tools-platforms",
    title: "Tools & Development Platforms",
    icon: Wrench,
    items: [
      "Visual Studio Code",
      "Jupyter Notebook",
      "Google Colab",
      "Kaggle",
      "Postman",
      "Microsoft Office",
      "Canva",
      "Figma",
    ],
  },
  {
    id: "cms-ecommerce",
    title: "CMS & E-Commerce",
    icon: Settings,
    items: [
      "WordPress",
      "Shopify",
      "Custom CMS Development",
      "Headless CMS Integration",
    ],
  },
  {
    id: "website-development",
    title: "Website Development",
    icon: Globe,
    items: [
      "Business Websites",
      "Corporate Websites",
      "Portfolio Websites",
      "E-Commerce Websites",
      "Landing Pages",
      "Custom Web Applications",
      "Admin Dashboards",
      "ERP & CRM Solutions",
      "SaaS Platforms",
      "API Integrations",
      "Payment Gateway Integration",
    ],
  },
  {
    id: "app-development",
    title: "App Development",
    icon: Smartphone,
    items: [
      "Android Applications",
      "iOS Applications",
      "Cross-Platform Applications",
      "Business Applications",
      "E-Commerce Applications",
      "On-Demand Service Apps",
    ],
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    icon: Megaphone,
    items: [
      "Technical SEO",
      "On-Page SEO",
      "Off-Page SEO",
      "Local SEO",
      "SEO Audits",
      "Google Ads",
      "Meta Ads (Facebook & Instagram)",
      "LinkedIn Ads",
      "PPC Campaign Management",
      "Social Media Marketing",
      "Social Media Management",
      "Content Marketing",
      "Email Marketing",
      "WhatsApp Marketing",
      "Google Business Profile Optimization",
      "Performance Marketing",
      "Lead Generation",
      "Conversion Rate Optimization (CRO)",
    ],
  },
  {
    id: "ui-ux-design",
    title: "UI/UX Design",
    icon: Palette,
    items: [
      "UI Design",
      "UX Design",
      "Wireframing",
      "Prototyping",
      "Responsive Design",
      "Mobile-First Design",
      "User Journey Design",
    ],
  },
  {
    id: "automation-business",
    title: "Automation & Business Solutions",
    icon: Bot,
    items: [
      "AI Workflow Automation",
      "Business Process Automation",
      "CRM Automation",
      "Chatbot Development",
      "Email Automation",
      "Workflow Integration",
    ],
  },
  {
    id: "core-engineering",
    title: "Core Software Engineering",
    icon: Sparkles,
    items: [
      "Full-Stack Development",
      "Object-Oriented Programming (OOP)",
      "Data Structures & Algorithms (DSA)",
      "Software Architecture",
      "Clean Code Principles",
      "Design Patterns",
      "Agile Development",
      "Version Control",
      "API Development",
      "System Integration",
      "Performance Optimization",
      "Security Best Practices",
    ],
  },
  {
    id: "professional-skills",
    title: "Professional Skills",
    icon: Users,
    items: [
      "Problem Solving",
      "Analytical Thinking",
      "Ownership Mindset",
      "Team Collaboration",
      "Communication",
      "Project Management",
      "Rapid Learning",
      "Client Requirement Analysis",
      "Technical Consulting",
    ],
  },
];

export const totalTechStackItems = techStackCategories.reduce(
  (sum, category) => sum + category.items.length,
  0
);
