import { Building2, Globe, Heart, Briefcase, Users, Brain, Eye, Trophy, Share2, BarChart3, GraduationCap, ShoppingBag, Dumbbell, BookOpen, MapPin } from "lucide-react";

export const projects = [
  {
    id: 11,
    title: "Exceptional IAS Academy - Coaching Institute Website",
    description: "A modern coaching institute website showcasing courses, faculty, results, and admissions with a clean, conversion-focused design.",
    detailedDescription: "A professional website for Exceptional IAS Academy designed to attract and inform aspiring civil services students. The platform highlights course offerings, experienced faculty, success stories, and study programs while making enquiry and admission simple. The design focuses on building trust and credibility with prospective students through clear information architecture and a responsive, fast-loading interface.",
    image: "/images/projects/exceptionalias.png",
    link: "https://www.exceptionaliasacademy.com/",
    technologies: ["Next.js", "TypeScript", "Style System", "NestJS", "MongoDB"],
    category: "Education Website",
    features: [
      "Course & Program Showcase",
      "Faculty Profiles & Expertise",
      "Student Success Stories",
      "Admission & Enquiry Forms",
      "Study Material Sections",
      "Mobile-Responsive Design",
      "Fast Loading & SEO Optimized",
      "Contact & Location Details"
    ],
    duration: "15 - 20 days",
    client: "Exceptional IAS Academy",
    icon: GraduationCap,
    color: "bg-blue-500"
  },
  {
    id: 12,
    title: "ShoesHub Poonch - Footwear E-Commerce Store",
    description: "A sleek online footwear store with product listings, categories, and a smooth shopping experience across all devices.",
    detailedDescription: "An attractive e-commerce website for ShoesHub Poonch, designed to showcase and sell footwear online. The store features organized product categories, detailed product pages, and an intuitive browsing experience. Built with a modern, mobile-first design, the platform helps customers easily discover products and place orders while giving the brand a strong online presence.",
    image: "/images/projects/shoeshub.png",
    link: "https://shoeshubpoonch.vercel.app/",
    technologies: ["Next.js", "TypeScript", "Style System", "NestJS", "PostgreSQL"],
    category: "E-Commerce Website",
    features: [
      "Product Listings & Categories",
      "Detailed Product Pages",
      "Shopping Cart Experience",
      "Search & Filter Options",
      "Mobile-First Responsive Design",
      "Fast Loading & SEO Optimized",
      "Brand Showcase & Offers",
      "Contact & Order Enquiry"
    ],
    duration: "15 - 20 days",
    client: "ShoesHub Poonch",
    icon: ShoppingBag,
    color: "bg-amber-500"
  },
  {
    id: 13,
    title: "FitSpace Gym - Fitness Center Website",
    description: "A bold, energetic gym website highlighting programs, trainers, memberships, and schedules with a motivating design.",
    detailedDescription: "A dynamic and energetic website for FitSpace Gym designed to inspire visitors to start their fitness journey. The platform showcases training programs, expert trainers, membership plans, and class schedules with a bold, motivating visual style. The responsive design ensures members can easily explore offerings and get in touch, helping the gym grow its community and memberships.",
    image: "/images/projects/fitspacegym.png",
    link: "https://fitspacegym.vercel.app/",
    technologies: ["Next.js", "TypeScript", "Style System", "Java", "MongoDB"],
    category: "Fitness Website",
    features: [
      "Training Programs Showcase",
      "Trainer Profiles",
      "Membership Plans & Pricing",
      "Class Schedules",
      "Gallery & Facilities",
      "Mobile-Responsive Design",
      "Fast Loading & SEO Optimized",
      "Contact & Join Enquiry Forms"
    ],
    duration: "15 - 20 days",
    client: "FitSpace Gym",
    icon: Dumbbell,
    color: "bg-red-500"
  },
  {
    id: 14,
    title: "Citadel Library - Library & Study Space Website",
    description: "A calm, well-structured website for a library and study space featuring memberships, seating, and resources.",
    detailedDescription: "A clean and organized website for Citadel Library designed to provide students and readers with information about study spaces, memberships, and available resources. The platform emphasizes a quiet, focused atmosphere through thoughtful design while making it easy to explore facilities, plans, and timings. The responsive interface ensures a smooth experience for visitors looking to reserve or learn about the space.",
    image: "/images/projects/citadel.png",
    link: "https://citadellibrary.vercel.app/",
    technologies: ["Next.js", "TypeScript", "Style System", "Node.js", "PostgreSQL"],
    category: "Library Website",
    features: [
      "Study Space & Seating Info",
      "Membership Plans & Pricing",
      "Facilities & Resources Showcase",
      "Timings & Availability",
      "Enquiry & Booking Forms",
      "Mobile-Responsive Design",
      "Fast Loading & SEO Optimized",
      "Contact & Location Details"
    ],
    duration: "15 - 20 days",
    client: "Citadel Library",
    icon: BookOpen,
    color: "bg-emerald-500"
  },
  {
    id: 1,
    title: "Dr. Jibran Bashir - Orthopedic Care Website",
    description: "A professional medical website showcasing services, expertise, and online appointment booking with a clean and responsive UI.",
    detailedDescription: "A comprehensive medical website designed for Dr. Jibran Bashir's orthopedic practice. The platform features a modern, clean interface that builds trust with patients while providing essential information about services, doctor's expertise, and treatment options. The website includes an integrated appointment booking system, patient testimonials, and detailed service pages.",
    image: "/images/projects/drjibran.png",
    link: "https://drjibranbashir.com",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion", "Responsive Design", "SEO Optimization"],
    category: "Medical Website",
    features: [
      "Online Appointment Booking System",
      "Service & Treatment Information",
      "Doctor's Profile & Expertise",
      "Patient Testimonials",
      "Contact Forms & Location Maps",
      "Mobile-Responsive Design",
      "Fast Loading & SEO Optimized",
      "Secure Patient Data Handling"
    ],
    duration: "2 months",
    client: "Dr. Jibran Bashir",
    icon: Building2,
    color: "bg-blue-500"
  },
  {
    id: 2,
    title: "Hotel Sea View - Luxury Stay Website",
    description: "A modern hotel website displaying rooms, gallery, and contact details with an attractive landing section and smooth navigation.",
    detailedDescription: "An elegant and luxurious website for Hotel Sea View, designed to showcase the hotel's premium accommodations and services. The website features stunning visual galleries, detailed room descriptions, amenities information, and an easy-to-use booking interface. The design emphasizes the hotel's luxury brand while maintaining excellent user experience across all devices.",
    image: "/images/projects/hotelseaview.png",
    link: "https://thehotelseaview.in",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Image Optimization", "Booking Integration", "Google Maps API"],
    category: "Hospitality Website",
    features: [
      "Interactive Room Gallery",
      "Online Booking System",
      "Amenities Showcase",
      "Location & Directions",
      "Contact & Inquiry Forms",
      "Responsive Mobile Design",
      "High-Quality Image Display",
      "Smooth Animations & Transitions"
    ],
    duration: "2.5 months",
    client: "Hotel Sea View",
    icon: Globe,
    color: "bg-amber-500"
  },
  {
    id: 3,
    title: "Kindness Towards Humanity Foundation",
    description: "A nonprofit organization website highlighting mission, team, gallery, and donation support with a user-friendly design.",
    detailedDescription: "A compassionate and impactful website for the Kindness Towards Humanity Foundation, designed to inspire visitors and facilitate donations. The platform effectively communicates the organization's mission, showcases their humanitarian work through galleries and stories, and provides secure donation options. The design balances emotional connection with clear calls-to-action.",
    image: "/images/projects/kindnesstowordshumanity.png",
    link: "/projects",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Payment Gateway Integration", "Content Management", "Social Media Integration"],
    category: "Nonprofit Website",
    features: [
      "Mission & Vision Pages",
      "Team & Volunteer Information",
      "Project Gallery & Stories",
      "Secure Donation System",
      "Event Calendar & Updates",
      "Contact & Volunteer Forms",
      "Social Media Integration",
      "Impact Reports & Transparency"
    ],
    duration: "3 months",
    client: "Kindness Towards Humanity Foundation",
    icon: Heart,
    color: "bg-red-500"
  },
  {
    id: 4,
    title: "Saibbyweb Office Management Dashboard",
    description: "A web-based system for managing employees, attendance, and documents with secure login and clean UI.",
    detailedDescription: "A comprehensive office management dashboard designed for Saibbyweb to streamline internal operations. The system includes employee management, attendance tracking, document storage, and administrative controls. Built with security and efficiency in mind, the dashboard provides a clean, intuitive interface for managing day-to-day office tasks and maintaining organizational records.",
    image: "/images/projects/office-management.png",
    link: "https://sw-office.vercel.app",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Authentication System", "Database Integration", "File Upload System", "Dashboard Analytics"],
    category: "Management System",
    features: [
      "Employee Management System",
      "Attendance Tracking & Reports",
      "Document Storage & Management",
      "Secure User Authentication",
      "Role-Based Access Control",
      "Dashboard Analytics",
      "File Upload & Download",
      "Admin Panel & Settings"
    ],
    duration: "4 months",
    client: "Saibbyweb",
    icon: Briefcase,
    color: "bg-purple-500"
  },
  {
    id: 15,
    title: "PlaceHub - Property Discovery Platform",
    description: "A trusted real-estate platform to buy, rent, and sell verified properties with confidence across Kashmir.",
    detailedDescription: "PlaceHub helps people discover places they'll love to live. The platform lists verified homes, apartments, land, shops, offices, and more with trusted agents, secure deals, and a clear search experience by location and property type. Built for buyers and sellers who want zero guesswork — from browsing featured listings to connecting with verified agents and finalizing the right property.",
    image: "/images/projects/placehub.png",
    link: "https://findyourperfectplace.vercel.app/",
    technologies: ["Next.js", "TypeScript", "Style System", "NestJS", "MongoDB"],
    category: "Real Estate Platform",
    features: [
      "Buy, Rent & Sell Listings",
      "Verified Property Catalogue",
      "Category-Based Exploration",
      "Location & Type Search",
      "Featured Properties Showcase",
      "Find Agents Directory",
      "List Your Property Flow",
      "Mobile-Responsive Design"
    ],
    duration: "1 - 2 months",
    client: "PlaceHub",
    icon: MapPin,
    color: "bg-gold-dark"
  },
  {
  id: 5,
  title: "Code2Concept - AI-Powered Manim Video Generator",
  description: "Transform code, algorithms, and technical concepts into animated educational videos using LLMs and Manim.",
  detailedDescription: "Code2Concept is an AI-powered educational content generation platform that automatically converts programming code, algorithms, and technical concepts into professional animated videos. The system leverages Large Language Models (LLMs) to analyze source code, generate explanations, create animation scripts, and render high-quality educational videos using Manim. It helps educators, students, and content creators quickly produce engaging visual explanations for complex topics without manually creating animations.",
  image: "/images/projects/code2concept.png",
  link: "/projects",
  technologies: [
    "Python",
    "Manim",
    "LLM Integration",
    "FastAPI",
    "React",
    "Next.js",
    "OpenAI API",
    "Video Processing",
    "Prompt Engineering",
    "AI Automation"
  ],
  category: "AI & Education Technology",
  features: [
    "Code-to-Animation Conversion",
    "LLM-Powered Concept Analysis",
    "Automatic Script Generation",
    "Manim Video Rendering",
    "Algorithm Visualization",
    "Educational Voiceover Generation",
    "Custom Animation Templates",
    "Export to MP4 & GIF",
    "Interactive Learning Content",
    "Real-Time Preview Dashboard"
  ],
  duration: "5 months",
  client: "Personal Project",
  icon: Brain,
  color: "bg-indigo-500"
},
{
  id: 6,
  title: "EyeAmHere - AI-Powered Smart Attendance System",
  description: "An intelligent attendance and classroom engagement platform that automatically tracks student presence, attention, and participation using Computer Vision and AI.",
  detailedDescription: "EyeAmHere is an AI-powered classroom intelligence system designed to revolutionize attendance management and student engagement tracking. The platform utilizes Computer Vision, face recognition, and machine learning algorithms to automatically identify students, mark attendance, monitor attentiveness, and analyze classroom participation in real time. By eliminating manual attendance processes, EyeAmHere helps educational institutions improve accuracy, save time, and gain valuable insights into student involvement and learning behavior.",
  image: "/images/projects/eyeamhere.png",
  link: "/projects",
  technologies: [
    "Python",
    "OpenCV",
    "Computer Vision",
    "Face Recognition",
    "Machine Learning",
    "FastAPI",
    "React",
    "MongoDB",
    "Real-Time Processing",
    "AI Analytics"
  ],
  category: "AI & Education Technology",
  features: [
    "Automatic Face Recognition Attendance",
    "Real-Time Student Detection",
    "Classroom Engagement Analysis",
    "Attention & Focus Monitoring",
    "Attendance Reports & Analytics",
    "Teacher Dashboard",
    "Student Participation Tracking",
    "Secure Student Database",
    "Real-Time Classroom Monitoring",
    "Performance Insights & Statistics"
  ],
  duration: "3 months",
  client: "Personal Project",
  icon: Eye,
  color: "bg-cyan-500",
},
{
  id: 7,
  title: "AlgoArena - AI-Powered Learning Platform",
  description: "An intelligent learning platform that personalizes education through AI-driven roadmaps, coding challenges, skill assessments, and adaptive learning experiences.",
  detailedDescription: "AlgoArena is an AI-powered learning ecosystem designed to help students and developers master technical skills efficiently. The platform leverages artificial intelligence to create personalized learning paths, recommend resources, analyze user performance, and generate adaptive coding challenges. With integrated progress tracking, interview preparation modules, and gamified learning experiences, AlgoArena provides a comprehensive environment for learners to enhance their programming, problem-solving, and career development skills.",
  image: "/images/projects/algoarena.png",
  link: "/projects",
  technologies: [
    "Next.js",
    "React",
    "TypeScript",
    "Node.js",
    "MongoDB",
    "OpenAI API",
    "Python",
    "Tailwind CSS",
    "AI Recommendation Engine",
    "Data Analytics"
  ],
  category: "AI & EdTech Platform",
  features: [
    "AI-Powered Personalized Learning Paths",
    "Adaptive Coding Challenges",
    "Skill Gap Analysis",
    "Interview Preparation Modules",
    "Progress Tracking Dashboard",
    "AI Learning Assistant",
    "Gamified Learning Experience",
    "Real-Time Performance Analytics",
    "Personalized Resource Recommendations",
    "Coding Contest & Leaderboards"
  ],
  duration: "4 months",
  client: "Personal Project",
  icon: Trophy,
  color: "bg-orange-500",
},
{
  id: 8,
  title: "ShareStore - Smart Resource Sharing Platform",
  description: "A centralized platform for students and professionals to securely store, organize, and share notes, documents, and learning resources without losing them in crowded chats.",
  detailedDescription: "ShareStore is a modern file and knowledge-sharing platform designed to solve the common problem of important notes, assignments, documents, and resources getting buried in busy WhatsApp, Telegram, and Discord conversations. The platform provides a centralized space where students, educators, and professionals can upload, organize, discover, and access files anytime. With advanced search, categorization, and collaboration features, ShareStore ensures valuable resources remain easily accessible and never get lost in endless chat threads.",
  image: "/images/projects/sharestore.png",
  link: "/projects",
  technologies: [
    "Next.js",
    "React",
    "Node.js",
    "MongoDB",
    "Express.js",
    "Cloud Storage",
    "JWT Authentication",
    "Tailwind CSS",
    "File Management System",
    "Search Engine"
  ],
  category: "Knowledge Sharing Platform",
  features: [
    "File Upload & Download",
    "Notes & Document Sharing",
    "Smart Resource Categorization",
    "Advanced Search Functionality",
    "User Profiles & Contributions",
    "Secure Authentication System",
    "Cloud-Based Storage",
    "Resource Bookmarking",
    "Department & Subject Wise Organization",
    "Community-Driven Knowledge Repository"
  ],
  duration: "2 months",
  client: "Personal Project",
  icon: Share2,
  color: "bg-emerald-500",
},
{
  id: 9,
  title: "Sales Analytics - AI Business Intelligence Dashboard",
  description: "An intelligent analytics platform that transforms raw business data into actionable insights through interactive dashboards, reports, and AI-driven recommendations.",
  detailedDescription: "Sales Analytics is a powerful business intelligence platform designed to help organizations understand their sales performance and make data-driven decisions. By simply uploading sales data in CSV format, businesses can visualize trends, monitor key performance indicators, identify high-performing products, analyze customer behavior, and uncover growth opportunities. The platform leverages analytics and AI-powered insights to help business owners quickly identify strengths, weaknesses, and areas requiring attention without needing advanced technical expertise.",
  image: "/images/projects/salesanalytics.png",
  link: "/projects",
  technologies: [
    "Python",
    "Streamlit",
    "Pandas",
    "NumPy",
    "Plotly",
    "Data Analytics",
    "Machine Learning",
    "CSV Processing",
    "Business Intelligence",
    "Data Visualization"
  ],
  category: "Business Intelligence & Analytics",
  features: [
    "CSV Data Upload & Processing",
    "Interactive Sales Dashboards",
    "Revenue & Profit Analysis",
    "Top Products Performance Tracking",
    "Customer Behavior Insights",
    "Sales Trend Forecasting",
    "AI-Powered Business Recommendations",
    "Real-Time Data Visualization",
    "KPI Monitoring & Reports",
    "Exportable Analytics Reports"
  ],
  duration: "1 month",
  client: "Personal Project",
  icon: BarChart3,
  color: "bg-green-500",
},
{
  id: 10,
  title: "DevVerse - Developer Social Network",
  description: "A social platform built for developers to connect, share ideas, discuss technologies, and collaborate on projects in a community-driven environment.",
  detailedDescription: "DevVerse is a modern social networking platform designed specifically for developers, programmers, and tech enthusiasts. Inspired by community-driven platforms like Threads, DevVerse enables users to share technical insights, discuss emerging technologies, post development updates, seek help from peers, and build meaningful professional connections. The platform fosters collaboration, knowledge sharing, and engagement through interactive discussions, developer-focused communities, and real-time communication features.",
  image: "/images/projects/devverse.png",
  link: "/projects",
  technologies: [
    "Next.js",
    "React",
    "Node.js",
    "Express.js",
    "MongoDB",
    "Socket.io",
    "JWT Authentication",
    "Tailwind CSS",
    "REST APIs",
    "Cloud Storage"
  ],
  category: "Social Networking Platform",
  features: [
    "Developer-Centric Social Feed",
    "Create & Share Technical Posts",
    "Real-Time Discussions",
    "Like, Comment & Repost System",
    "Developer Profiles & Portfolios",
    "Follow Developers & Communities",
    "Project Showcase Section",
    "Direct Messaging",
    "Technology-Based Communities",
    "Trending Topics & Discover Feed"
  ],
  duration: "2 months",
  client: "Personal Project",
  icon: Users,
  color: "bg-violet-500",
}
];
